[package]
name = "qubic_engine"
license = "MIT"
author = ["epaperamic@gmail.com"]
version = "0.1.7"
edition = "2024"
description = "qubic engine"
repository = "https://github.com/aokyut/qubic_engine"
keywords = ["engine", "game"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
ndarray = "0.16.1"
proconio = "0.5.0"
serde = { version = "= 1.0.193", features = ["derive"] }
serde_json = "1.0.108"
minimum_ml = { version = "0.1.9", features = ["full"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlite = "0.36.1"
rand = "0.8.5"
rand_distr = "0.4.3"
indicatif = "0.17.8"

# wasm時
[target.'cfg(target_arch = "wasm32")'.dependencies]
fastrand = "2.3.0"


[features]
default = []
render = []
slow = []
view = []
view_detail = []
search_profile = []

[profile.release]
opt-level = 3
lto = "fat"        # 完全なリンク時最適化
codegen-units = 1  # 最大限最適化（ビルド時間は増える）
debug = false      # デバッグ情報なし
strip = true       # シンボル削除
panic = "abort"    # unwind不要ならabortで軽量化

[profile.profiling]
inherits = "release"
debug = 1